matrix_includes.json: Replace the py310-cov with py311-cov.
It's to fix the issue below.
https://github.com/junaruga/rpm-py-installer/actions/runs/3507961554/jobs/5876036926#step:10:360

```
E               install.CmdError: CMD: [/work/.tox/py310-cov/bin/python setup.py -q build], Return Code: [1] at [/tmp/tmpifmn6s4t-rpm-py-installer/rpm-rpm-4.18.0-release/python] Stderr: [/work/.tox/py310-cov/lib64/python3.10/site-packages/coverage/inorout.py:472: CoverageWarning: --include is ignored because --source is set (include-ignored)
E                 self.warn("--include is ignored because --source is set", slug="include-ignored")
E               In file included from header-py.c:1:
E               rpmsystem-py.h:9:10: fatal error: Python.h: No such file or directory
E                   9 | #include <Python.h>
E                     |          ^~~~~~~~~~
E               compilation terminated.
E               error: command '/usr/bin/gcc' failed with exit code 1
E               ]
```